version: '3.8'

services:
 secret-santa:
  build:
   context: .
   dockerfile: Dockerfile
  image: secret-santa-app:dev
  container_name: secret-santa-dev
  ports:
   - '3000:3000'
  volumes:
   # Mount the project into the container for live development
   - ./:/app:cached
   # Persist test/dev database between restarts
   - secret-santa-data:/app/data
  environment:
   - NODE_ENV=development
   - DB_DIR=/app/data
   - PORT=3000
   - DOMAIN=${DOMAIN:-http://localhost:3000}
   - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
   - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
   - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
   - SMTP_SERVER=${SMTP_SERVER:-}
   - SMTP_PORT=${SMTP_PORT:-587}
   - SMTP_USERNAME=${SMTP_USERNAME:-}
   - SMTP_PASSWORD=${SMTP_PASSWORD:-}
   - FROM_EMAIL=${FROM_EMAIL:-}
  # Run the development server inside the container
  command: sh -c "npm install --no-audit --no-fund && npm run dev"
  healthcheck:
   test: ['CMD', 'node', '-e', "require('http').get('${DOMAIN:-http://localhost:3000}/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
   interval: 30s
   timeout: 10s
   retries: 3
   start_period: 40s

volumes:
 secret-santa-data:
  driver: local
