version: '3.8'

services:
 secret-santa:
  build:
   context: .
   dockerfile: Dockerfile
  image: secret-santa-app:latest
  container_name: secret-santa
  # This repository now provides two Docker Compose files:
  # - docker-compose.prod.yml  (production-ready, uses env + optional Docker secrets)
  # - docker-compose.dev.yml   (development-friendly, mounts source and runs the dev server)
  #
  # To run development:
  #   docker compose -f docker-compose.dev.yml up --build
  #
  # To run production (build & run image):
  #   docker compose -f docker-compose.prod.yml up --build -d

  # The original configuration has been moved into the two files above. Pick the one
  # that fits your use case. See their headers for details.
