name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work
      placeholder: |
        For example:
        1. User navigates to...
        2. Clicks on...
        3. System performs...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If applicable, add mockups or screenshots to help visualize the feature
      placeholder: Drag and drop images here

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Critical for my use case
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Affected Area
      description: Which part of the application does this relate to?
      multiple: true
      options:
        - Authentication
        - Pools Management
        - People Management
        - Wishlist
        - Restrictions
        - Assignment Generation
        - Email Notifications
        - History/Analytics
        - UI/UX
        - API
        - Docker/Deployment
        - Documentation
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: false